name: Python Lint

on: [pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.16.1
